# Generated by Django 6.0.5 on 2026-06-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompressionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('depth', models.FloatField(help_text='Depth in meters')),
                ('duration', models.FloatField(help_text='Duration in minutes')),
                ('order_number', models.IntegerField(help_text='Order number for sorting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decompression_models', to='dives.dive')),
            ],
        ),
    ]
