# Generated by Django 6.0.5 on 2026-06-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasMixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('oxygen_percentage', models.FloatField(help_text='Oxygen percentage in the gas mixture')),
                ('nitrogen_percentage', models.FloatField(help_text='Nitrogen percentage in the gas mixture')),
            ],
        ),
    ]
