# Generated by Django 6.0.5 on 2026-06-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='dives.dive')),
            ],
        ),
    ]
