# Generated by Django 6.0.5 on 2026-06-09 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gases', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('depth', models.FloatField()),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('temperature', models.FloatField(help_text='Temperature in Celsius')),
                ('location', models.CharField(max_length=255)),
                ('ascent_Speed', models.FloatField(help_text='Ascent speed in meters per minute')),
                ('status', models.CharField(choices=[('PL', 'Planned'), ('IP', 'In Progress'), ('CO', 'Completed'), ('CA', 'Cancelled')], default='PL', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gas_mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='gases.gasmixture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dives', to='users.user')),
            ],
        ),
    ]
