# Generated by Django 6.0.5 on 2026-07-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dive',
            old_name='ascent_Speed',
            new_name='ascent_speed',
        ),
    ]
